import { Suspense } from "react";

import type { Metadata } from "next";
import { DM_Sans, Geist } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

import { Toaster } from "sonner";
import "./globals.css";
import Providers from "./providers";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en" className={cn("font-sans", geist.variable)}
      >
        <body className={`${dmSans.className}`}>
          <Providers>
            <TooltipProvider>
              <Suspense fallback={null}>
                <div className="root-layout">
                  {children}
                </div>
              </Suspense>
              <Toaster richColors closeButton />
            </TooltipProvider>
          </Providers>
        </body>
      </html >
    </ClerkProvider>
  );
}
